### ISSUE TITLE
Client: Get all the posts from DB and show them on client-side

### ISSUE THREAD

**Issue by poswalsameer** [poswalsameer/CampusBurn#24]
### Feature Description:
We need to fetch all the posts available inside the DB and show them on the client side. The API endpoint is already created, so no need to change anything there. You just need to make an `axios` request, get the response, and map over it to show on the UI.

### Expected outcome:
The middle part of the `feed` page should contain all the posts.

### Screenshots:
Please attach relevant screenshots in your PR.

### Extra information:
No need to change anything inside `server` folder.

**Comment by Kalp-Chaniyara** [comment]
@poswalsameer i am working on it, please assign this issue to me

**Comment by poswalsameer** [comment]
> @poswalsameer i am working on it, please assign this issue to me

Hi, thanks for reaching out. This issue is half done and there is some issue on the API from the server-side. So, I am working on that right now. You can surely pick up any other issue if you want to. I will assign that to you.
