### ISSUE TITLE
Client: Redesign the Signup and Login forms

### ISSUE THREAD

**Issue by poswalsameer** [poswalsameer/CampusBurn#3]
### Description:
The current design for `signup` and `login` forms looks okay but it would be really nice if you someone could come up with a new design that aligns with the color scheme of the whole application ( using tones of blue, black and orange ). All the changes are needed to be done inside the `client` folder.

**Comment by vivek-inavalli** [comment]
from where I can get these 
CLOUDINARY_CLOUD_NAME = 
CLOUDINARY_API_KEY = 
CLOUDINARY_API_SECRET =

**Comment by poswalsameer** [comment]
> from where I can get these CLOUDINARY_CLOUD_NAME = CLOUDINARY_API_KEY = CLOUDINARY_API_SECRET =

You need to create a Cloudinary account from here  - [Cloudinary](https://cloudinary.com/home)
After signing up, go to your account, then API keys, and create one of yours.

Save all the details in your `.env` file, and then you are good to go.

Btw, thanks for reminding me to create an `.env.example` for the ease of all the contributors.
